version: '3'
services:
  app:
    build: .
    command: [ "go", "run", "main.go" ]
    depends_on:
      - db
    environment: 
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres # default values of postgres image
  db:
    environment: 
      POSTGRES_PASSWORD: postgres
    image: "postgres" 
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data: # named volumes can be managed easier using docker-compose